name: Publish to GitHub Packages

on:
  push:
    branches:
      - dev-pablo

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: yarn install
        run: yarn install
      - name: yarn build
        run: yarn build
      - name: yarn publish
        run: yarn publish

      - name: Publish packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
          lerna publish from-package --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
